/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Formularios;

import Util.PosicionFormulario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
// import java.awt.Dimension;
// import java.awt.Toolkit;

/**
 *
 * @author Juan Luis Diaz Aylas
 */
public class FrmPrincipal extends javax.swing.JFrame {
   
    private JLabel statusBar;
    private JPanel panelStatus;

    PosicionFormulario form = new PosicionFormulario();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Sistema de Control de Equipos de Computo");
        // Asegurar layout correcto
      //  this.getContentPane().setLayout(new BorderLayout());
        crearBarraDeEstado();

     
       
    }

  /**
     * Crea una barra de estado en la parte inferior de la ventana
     */
    private void crearBarraDeEstado() {
        
    String username = System.getProperty("user.name");
    String hostname = "Desconocido";

    try {
        hostname = InetAddress.getLocalHost().getHostName();
    } catch (Exception e) {
        hostname = "Error";
    }

    // Creamos etiqueta
    statusBar = new JLabel("  Usuario: " + username + "  |  Máquina: " + hostname);
    statusBar.setFont(new Font("SansSerif", Font.PLAIN, 12));
    statusBar.setForeground(Color.BLACK); // asegúrate de que el texto se vea


    // Configuramos panel de estado
    panelStatus = new JPanel(new BorderLayout());
    panelStatus.setPreferredSize(new Dimension(getWidth(), 24));
    panelStatus.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    panelStatus.setBackground(new Color(240, 240, 240)); // gris claro neutro
    panelStatus.add(statusBar, BorderLayout.WEST);
    

    // AÑADIMOS a jPanelPrincipal que usa BorderLayout (desde el diseñador)
    escritorio.add(panelStatus, BorderLayout.SOUTH);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        lblcantidad = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuSistema = new javax.swing.JMenu();
        menuItemBaseDatos = new javax.swing.JMenuItem();
        jMenuRegistrar = new javax.swing.JMenu();
        menuItemUsuario = new javax.swing.JMenuItem();
        MenuCategoria = new javax.swing.JMenuItem();
        MenuMarca = new javax.swing.JMenuItem();
        MnUniMedida = new javax.swing.JMenuItem();
        MnArticulo = new javax.swing.JMenuItem();
        MnProcesador = new javax.swing.JMenuItem();
        MenuDiscoDuro = new javax.swing.JMenuItem();
        MnCargo = new javax.swing.JMenuItem();
        MnArea = new javax.swing.JMenuItem();
        jMenuModificar = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuConsultaPesos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Items :");
        escritorio.add(jLabel7);
        jLabel7.setBounds(50, 450, 35, 16);

        lblcantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcantidad.setText("00");
        escritorio.add(lblcantidad);
        lblcantidad.setBounds(10, 450, 14, 16);

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini_engrane.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Mantenimiento");

        jMenuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini_sistema.png"))); // NOI18N
        jMenuSistema.setText("Sistema");

        menuItemBaseDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini_bd.png"))); // NOI18N
        menuItemBaseDatos.setMnemonic('o');
        menuItemBaseDatos.setText("Configurar Base de Datos");
        menuItemBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBaseDatosActionPerformed(evt);
            }
        });
        jMenuSistema.add(menuItemBaseDatos);

        fileMenu.add(jMenuSistema);

        jMenuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar1.png"))); // NOI18N
        jMenuRegistrar.setText("Registrar");

        menuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administrador.png"))); // NOI18N
        menuItemUsuario.setText("Registrar Usuario");
        menuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(menuItemUsuario);

        MenuCategoria.setText("Registrar Categoria");
        MenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MenuCategoria);

        MenuMarca.setText("Registrar Marca");
        MenuMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMarcaActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MenuMarca);

        MnUniMedida.setText("Registrar Unidad de Medida");
        MnUniMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUniMedidaActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MnUniMedida);

        MnArticulo.setText("Registrar Articulo");
        MnArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnArticuloActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MnArticulo);

        MnProcesador.setText("Registrar Procesador");
        MnProcesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProcesadorActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MnProcesador);

        MenuDiscoDuro.setText("Registrar Disco Duro");
        MenuDiscoDuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDiscoDuroActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MenuDiscoDuro);

        MnCargo.setText("Registrar Cargo");
        MnCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCargoActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MnCargo);

        MnArea.setText("Registrar Area");
        MnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAreaActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(MnArea);

        fileMenu.add(jMenuRegistrar);

        jMenuModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini_editar.png"))); // NOI18N
        jMenuModificar.setText("Modificar");
        fileMenu.add(jMenuModificar);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Consulta");

        jMenuItem2.setText("jMenuItem2");
        helpMenu.add(jMenuItem2);

        menuBar.add(helpMenu);

        jMenu2.setText("Orden de Produccion");

        jMenuItem5.setText("Modificar Orden de Produccion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        menuBar.add(jMenu2);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mini_reporte.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Reporte");

        jMenuConsultaPesos.setMnemonic('y');
        jMenuConsultaPesos.setText("Consulta de Pesos");
        jMenuConsultaPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaPesosActionPerformed(evt);
            }
        });
        editMenu.add(jMenuConsultaPesos);

        menuBar.add(editMenu);

        jMenu4.setText("Backup");
        jMenu4.add(jSeparator3);

        menuBar.add(jMenu4);

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Acerca de ...");
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(Salir);

        menuBar.add(jMenuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuarioActionPerformed
        // TODO add your handling code here:
        Formularios.FrmUsuarios pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmUsuarios(), escritorio);
    }//GEN-LAST:event_menuItemUsuarioActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
    
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuConsultaPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaPesosActionPerformed
        // TODO add your handling code here:
      //  Presentacion.Reportes.FrmConsultaPesos pantalla;
       // form.abrirFormulario(pantalla = new Presentacion.Reportes.FrmConsultaPesos(), escritorio);
    }//GEN-LAST:event_jMenuConsultaPesosActionPerformed

    private void menuItemBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBaseDatosActionPerformed
        // TODO add your handling code here:
          Sistema.FrmConfigurarDB pantalla;
          form.abrirFormulario(pantalla = new Sistema.FrmConfigurarDB(), escritorio);
    }//GEN-LAST:event_menuItemBaseDatosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       int respuesta = JOptionPane.showConfirmDialog(
            FrmPrincipal.this,
            "¿Estás seguro de que deseas salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
    if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0);
    } // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void MenuMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMarcaActionPerformed
        // TODO add your handling code here:
        Formularios.FrmMarca pantalla;
        form.abrirFormulario(pantalla = new FrmMarca(), escritorio);
    }//GEN-LAST:event_MenuMarcaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MenuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaActionPerformed
        // TODO add your handling code here:
        Formularios.FrmCategoriaMarca pantalla;
        form.abrirFormulario(pantalla = new FrmCategoriaMarca(), escritorio);
    }//GEN-LAST:event_MenuCategoriaActionPerformed

    private void MnUniMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUniMedidaActionPerformed
        // TODO add your handling code here:
        Formularios.FrmUnidadMedida pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmUnidadMedida(), escritorio);
    }//GEN-LAST:event_MnUniMedidaActionPerformed

    private void MnArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnArticuloActionPerformed
        // TODO add your handling code here:
        Formularios.FrmArticulos pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmArticulos(), escritorio);
    }//GEN-LAST:event_MnArticuloActionPerformed

    private void MenuDiscoDuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDiscoDuroActionPerformed
        // TODO add your handling code here:
            Formularios.FrmDiscoDuro pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmDiscoDuro(), escritorio);
    }//GEN-LAST:event_MenuDiscoDuroActionPerformed

    private void MnCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCargoActionPerformed
        // TODO add your handling code here:
          Formularios.FrmCargo pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmCargo(), escritorio);
    }//GEN-LAST:event_MnCargoActionPerformed

    private void MnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAreaActionPerformed
        // TODO add your handling code here:
         Formularios.FrmSistemaPension pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmSistemaPension(), escritorio);
    }//GEN-LAST:event_MnAreaActionPerformed

    private void MnProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProcesadorActionPerformed
        // TODO add your handling code here:
         Formularios.FrmProcesador pantalla;
        form.abrirFormulario(pantalla = new Formularios.FrmProcesador(), escritorio);
    }//GEN-LAST:event_MnProcesadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCategoria;
    private javax.swing.JMenuItem MenuDiscoDuro;
    private javax.swing.JMenuItem MenuMarca;
    private javax.swing.JMenuItem MnArea;
    private javax.swing.JMenuItem MnArticulo;
    private javax.swing.JMenuItem MnCargo;
    private javax.swing.JMenuItem MnProcesador;
    private javax.swing.JMenuItem MnUniMedida;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuConsultaPesos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jMenuModificar;
    private javax.swing.JMenu jMenuRegistrar;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemBaseDatos;
    private javax.swing.JMenuItem menuItemUsuario;
    // End of variables declaration//GEN-END:variables

}
